# Generated by Django 3.2.12 on 2022-04-22 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0161_alter_inventorydocument_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyauditlog',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propertyauditlog_parent1', to='seed.propertyauditlog'),
        ),
        migrations.AlterField(
            model_name='propertyauditlog',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propertyauditlog_parent2', to='seed.propertyauditlog'),
        ),
        migrations.AlterField(
            model_name='propertyauditlog',
            name='parent_state1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_state1', to='seed.propertystate'),
        ),
        migrations.AlterField(
            model_name='propertyauditlog',
            name='parent_state2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_state2', to='seed.propertystate'),
        ),
    ]
